version: '3.8'

services:
  claude-skill-tree:
    build: .
    container_name: claude-skill-tree
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - skill-tree-db:/app/database
      - ${USERPROFILE}/Memory Database/Claude:/external-memory:ro
    environment:
      - NODE_ENV=production
      - SKILL_DB_PATH=/app/data/skill_tree.db
      - MEMORY_SYNC_PATH=/external-memory
      - ANALYTICS_ENABLED=true
      - TELEMETRY_LEVEL=detailed
      - HARVEY_OPTIMIZATION=true
      - CONTEXT_PRESERVATION=enhanced
      - LIMITATION_OVERRIDE=active
    ports:
      - "9090:9090"  # Metrics port
      - "7865:7865"  # MCP communication port
    networks:
      - claude-network
    labels:
      - "anthropic.component=analytics"
      - "anthropic.subsystem=skill-tree"
      - "monitoring.enabled=true"
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  skill-tree-ui:
    image: nginx:alpine
    container_name: skill-tree-ui
    volumes:
      - ./ui:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    networks:
      - claude-network
    labels:
      - "anthropic.component=analytics-ui"
      - "anthropic.subsystem=visualization"

networks:
  claude-network:
    driver: bridge
    name: claude-analytics-network

volumes:
  skill-tree-db:
    driver: local
    name: claude-skill-tree-database